method:
  options:
    mandatory_periods:
      - 292
    total_periods: 365
    sampling_time: "Hour(1)"
    representative_periods: 1
    time_steps_per_period: 24
  optimization:
    binary_ordering: false
    time_series_error:
      weight: 1
      type: "absolute"
    integral_weights: false
    equal_weights: false
results:
  save_results: true
  result_dir: "output_1_repr_days"
  create_plots: true
base_dir: "c:\\Users\\kbruninx\\Code\\eu-ets-power-sector-hydrogen-industry\\Input"
time_series:
  default:
    weight: 1
    source: "timeseries_May2018.csv"
    start: 1
    interpolation_type: "linear"
    sampling_time: "Hour(1)"
    csv_options:
      delim: ","
    timestamp: "Datetime"
  Other:
    value_column: "OTHER"
  Load:
    value_column: "LOAD"
  WindOnshore:
    value_column: "WIND_OFFSHORE"
  Solar:
    value_column: "SOLAR"
