method:
  options:
    mandatory_periods:
      - 5
      - 20
      - 81
      - 93
      - 118
      - 207
      - 304
      - 306
    total_periods: 365
    sampling_time: "Hour(1)"
    representative_periods: 8
    time_steps_per_period: 24
  optimization:
    binary_ordering: false
    time_series_error:
      weight: 1
      type: "absolute"
    integral_weights: false
    equal_weights: false
results:
  save_results: true
  result_dir: "output_8_repr_days"
  create_plots: true
base_dir: "c:\\Users\\kbruninx\\Code\\eu-ets-power-sector-hydrogen-industry\\Input"
time_series:
  WindOffshore:
    value_column: "WIND_OFFSHORE"
  default:
    weight: 1
    source: "timeseries.csv"
    start: 1
    interpolation_type: "linear"
    sampling_time: "Hour(1)"
    csv_options:
      delim: ";"
    timestamp: "Datetime"
  Other:
    value_column: "OTHER"
  Load:
    value_column: "LOAD"
  WindOnshore:
    value_column: "WIND_ONSHORE"
  Solar:
    value_column: "SOLAR"
